In [1]:
import numpy as np
import pandas as pd

In [2]:
ar = np.array(np.arange(2,8))
ar

array([2, 3, 4, 5, 6, 7])

In [3]:
type(ar)

numpy.ndarray

In [4]:
ar2 = np.array([[1,2,3,4],
[7,8,9,0]])

In [5]:
ar.ndim

1

In [6]:
ar2

array([[1, 2, 3, 4],
       [7, 8, 9, 0]])

In [7]:
type(ar2)

numpy.ndarray

In [8]:
ar2.ndim

2

In [9]:
ar.shape, ar2.shape

((6,), (2, 4))

In [10]:
ar.dtype, ar2.dtype

(dtype('int32'), dtype('int32'))

In [11]:
ar.size, ar2.size

(6, 8)

In [12]:
pd.DataFrame(ar2)

0  1  2  3
0  1  2  3  4
1  7  8  9  0

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.random.randint(2,10, size=(4,3))

array([[7, 5, 6],
       [2, 7, 7],
       [8, 6, 8],
       [7, 7, 6]])

In [17]:
np.random.random(size=(3,4))

array([[0.98681062, 0.53932072, 0.67778807, 0.23958059],
       [0.50507317, 0.89016219, 0.1153861 , 0.28547143],
       [0.94516774, 0.45376868, 0.52262109, 0.42183834]])

In [18]:
np.random.rand(3,4) # another way for above command

array([[0.31312917, 0.33569175, 0.09693103, 0.20200585],
       [0.90059333, 0.42865485, 0.13699384, 0.73112074],
       [0.07866849, 0.17489625, 0.69713753, 0.32896937]])

In [19]:
# pseudo random numbers
np.random.seed(seed = 0)
np.random.rand(4,4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [20]:
arr = np.random.randint(10, 100, (4,4))
arr

array([[90, 79, 89, 57],
       [74, 92, 98, 59],
       [39, 29, 29, 24],
       [49, 42, 75, 19]])

In [21]:
np.unique(arr)

array([19, 24, 29, 39, 42, 49, 57, 59, 74, 75, 79, 89, 90, 92, 98])

In [22]:
arr[1]

array([74, 92, 98, 59])

In [23]:
ls

 Volume in drive E is Working Drive
 Volume Serial Number is 6075-2DD5

 Directory of E:\Udemy\Udemy - Data Science and Machine Learning\Complete Machine Learning &amp; Data Science Bootcamp 2021\ML Practice Projects

06-08-2021  09:22    <DIR>          .
06-08-2021  09:22    <DIR>          ..
03-08-2021  21:25    <DIR>          .ipynb_checkpoints
02-08-2021  19:57               369 car-sales.csv
03-08-2021  19:39               371 exported-car-sales.csv
06-08-2021  09:22            33,838 Numpy Intro.ipynb
03-08-2021  20:18           154,260 Pandas Intro.ipynb
               4 File(s)        188,838 bytes
               3 Dir(s)  96,917,405,696 bytes free


In [24]:
%who

ar	 ar2	 arr	 np	 pd	 


In [25]:
ar2

array([[1, 2, 3, 4],
       [7, 8, 9, 0]])

In [26]:
arr3d = np.random.randint(10,100, size = (5,2,3,3))
arr3d

array([[[[67, 42, 41],
         [84, 33, 45],
         [85, 65, 38]],

        [[44, 10, 10],
         [46, 63, 15],
         [48, 27, 89]]],


       [[[14, 52, 68],
         [41, 11, 75],
         [51, 67, 45]],

        [[21, 56, 92],
         [10, 24, 63],
         [22, 52, 94]]],


       [[[85, 78, 16],
         [78, 57, 13],
         [86, 62, 88]],

        [[25, 30, 68],
         [33, 89, 23],
         [95, 58, 59]]],


       [[[79, 51, 45],
         [74, 79, 10],
         [60, 46, 44]],

        [[58, 13, 52],
         [87, 31, 83],
         [10, 20, 53]]],


       [[[68, 33, 69],
         [12, 72, 45],
         [77, 92, 56]],

        [[30, 91, 60],
         [37, 24, 51],
         [68, 75, 46]]]])

In [27]:
arr3d.ndim, arr3d.shape, arr3d.size, arr3d.dtype

(4, (5, 2, 3, 3), 90, dtype('int32'))

In [28]:
arr3d[:3,:,:2,:2]

array([[[[67, 42],
         [84, 33]],

        [[44, 10],
         [46, 63]]],


       [[[14, 52],
         [41, 11]],

        [[21, 56],
         [10, 24]]],


       [[[85, 78],
         [78, 57]],

        [[25, 30],
         [33, 89]]]])

## Arithmetic operations

In [29]:
arr

array([[90, 79, 89, 57],
       [74, 92, 98, 59],
       [39, 29, 29, 24],
       [49, 42, 75, 19]])

In [30]:
arr +2

array([[ 92,  81,  91,  59],
       [ 76,  94, 100,  61],
       [ 41,  31,  31,  26],
       [ 51,  44,  77,  21]])

In [31]:
arr -2, arr +3

(array([[88, 77, 87, 55],
        [72, 90, 96, 57],
        [37, 27, 27, 22],
        [47, 40, 73, 17]]),
 array([[ 93,  82,  92,  60],
        [ 77,  95, 101,  62],
        [ 42,  32,  32,  27],
        [ 52,  45,  78,  22]]))

In [32]:
arr3d

array([[[[67, 42, 41],
         [84, 33, 45],
         [85, 65, 38]],

        [[44, 10, 10],
         [46, 63, 15],
         [48, 27, 89]]],


       [[[14, 52, 68],
         [41, 11, 75],
         [51, 67, 45]],

        [[21, 56, 92],
         [10, 24, 63],
         [22, 52, 94]]],


       [[[85, 78, 16],
         [78, 57, 13],
         [86, 62, 88]],

        [[25, 30, 68],
         [33, 89, 23],
         [95, 58, 59]]],


       [[[79, 51, 45],
         [74, 79, 10],
         [60, 46, 44]],

        [[58, 13, 52],
         [87, 31, 83],
         [10, 20, 53]]],


       [[[68, 33, 69],
         [12, 72, 45],
         [77, 92, 56]],

        [[30, 91, 60],
         [37, 24, 51],
         [68, 75, 46]]]])

In [33]:
arr3d.shape

(5, 2, 3, 3)

In [34]:
## Aggregation = peforming the same operation on a number of things
arr **2

array([[8100, 6241, 7921, 3249],
       [5476, 8464, 9604, 3481],
       [1521,  841,  841,  576],
       [2401, 1764, 5625,  361]], dtype=int32)

In [35]:
np.square(arr)

array([[8100, 6241, 7921, 3249],
       [5476, 8464, 9604, 3481],
       [1521,  841,  841,  576],
       [2401, 1764, 5625,  361]], dtype=int32)

Use Numpy methods on numpy elements: `function()`and Use Python methods on python elements: `np.function()`

In [36]:
%timeit arr **2
%timeit np.square(arr)

3.3 µs ± 258 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.17 µs ± 473 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))

944
19
98
59.0
673.125
25.944652628239215


In [38]:
arr

array([[90, 79, 89, 57],
       [74, 92, 98, 59],
       [39, 29, 29, 24],
       [49, 42, 75, 19]])

In [39]:
arr.T

array([[90, 74, 39, 49],
       [79, 92, 29, 42],
       [89, 98, 29, 75],
       [57, 59, 24, 19]])

# Dot Product

In [40]:
mat1 = np.random.randint(9, size = (3,3))
mat2 = np.random.randint(9, size = (3,3))

In [41]:
mat1

array([[6, 8, 2],
       [3, 0, 0],
       [6, 0, 6]])

In [42]:
mat2

array([[3, 3, 8],
       [8, 8, 2],
       [3, 2, 0]])

In [43]:
# Element wise operation - Hadamard Product
mat1 * mat2

array([[18, 24, 16],
       [24,  0,  0],
       [18,  0,  0]])

In [44]:
mat1.shape, mat2.shape

((3, 3), (3, 3))

In [45]:
# Dot product - Matrix Multiplication
np.dot(mat1, mat2)

array([[88, 86, 64],
       [ 9,  9, 24],
       [36, 30, 48]])

In [46]:
sale_info = np.random.randint(20,99, size = (4,3))

In [47]:
fruit_df = pd.DataFrame(sale_info, index=('Mon', 'Tues', 'Wed', 'Thur'), columns=('Apple', 'Lychee', 'Papaya'))

In [48]:
fruit_df

Apple  Lychee  Papaya
Mon      60      92      39
Tues     92      46      86
Wed      72      87      81
Thur     34      24      87

In [49]:
prices = np.random.randint(100, 999, size=(1,3))
prices

array([[849, 239, 698]])

In [50]:
price_df = pd.DataFrame(prices, columns=('Apple', 'Lychee', 'Papaya'))

In [51]:
price_df

Apple  Lychee  Papaya
0    849     239     698

In [52]:
sale_info.shape, prices.shape

((4, 3), (1, 3))

In [53]:
total = np.dot(sale_info, prices.T)

In [54]:
tot_df = pd.DataFrame(total, index=('Mon', 'Tues', 'Wed', 'Thur'))
tot_df

0
Mon   100150
Tues  149130
Wed   138459
Thur   95328

In [55]:
fruit_df['Total Prices'] = total
fruit_df

Apple  Lychee  Papaya  Total Prices
Mon      60      92      39        100150
Tues     92      46      86        149130
Wed      72      87      81        138459
Thur     34      24      87         95328

In [61]:
random_array = np.random.randint(9,size=(4,3))

In [62]:
random_array

array([[6, 5, 7],
       [8, 8, 2],
       [8, 6, 6],
       [1, 6, 8]])

In [63]:
np.sort(random_array)

array([[5, 6, 7],
       [2, 8, 8],
       [6, 6, 8],
       [1, 6, 8]])

In [64]:
np.argsort(random_array)

array([[1, 0, 2],
       [2, 0, 1],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [65]:
np.argmax(random_array, axis=1)

array([2, 0, 0, 2], dtype=int64)

### Reading Images as numbers

<img src = '04-nature_721703848.jpg'>

In [66]:
from matplotlib.image import imread

In [67]:
nature = imread("04-nature_721703848.jpg")

In [68]:
nature.dtype

dtype('uint8')

In [69]:
type(nature)

numpy.ndarray

In [71]:
nature.size, nature.shape, nature.ndim

(388800, (270, 480, 3), 3)

In [75]:
nature[:,:, :2]

array([[[  0,  93],
        [  3,  92],
        [  8,  91],
        ...,
        [  9, 149],
        [ 12, 134],
        [ 17, 118]],

       [[ 14,  88],
        [ 11,  81],
        [  6,  72],
        ...,
        [ 17, 136],
        [ 14, 139],
        [ 11, 141]],

       [[ 10,  78],
        [ 10,  74],
        [  8,  70],
        ...,
        [ 17, 125],
        [ 10, 135],
        [  4, 144]],

       ...,

       [[  3,  38],
        [  4,  39],
        [  5,  40],
        ...,
        [  4,  37],
        [  3,  50],
        [  6,  69]],

       [[  4,  37],
        [  4,  39],
        [  3,  40],
        ...,
        [  4,  35],
        [  4,  47],
        [  4,  67]],

       [[  4,  37],
        [  4,  39],
        [  3,  40],
        ...,
        [  5,  32],
        [  6,  44],
        [  2,  65]]], dtype=uint8)